package roupa.modelo.modelagem;

public enum TipoFechamento {
	ZIPER_LATERAL,
	ZIPER_FRENTE,
	ZIPER_COSTAS,
	BOTAO_LATERAL,
	BOTAO_FRENTE,
	BOTAO_COSTAS,
	FITA_LATERAL,
	FITA_FRENTE,
	FITA_COSTAS,
	COLCHETE_LATERAL,
	COLCHETE_FRENTE,
	COLCHETE_COSTAS,
	NAO_POSSUI
	
}
